### ISSUE TITLE
scrollbars

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#38]
for some reason my local version only has one scrollbar, but live doesn't even though i pushed it. the mistake was that I used multiple / nested `md-content` divs...

![two_scrollbars](https://cloud.githubusercontent.com/assets/6129121/14887655/fdbb55c8-0d56-11e6-94c9-5c1d9a984ca2.png)
![one_scrollbar](https://cloud.githubusercontent.com/assets/6129121/14887654/fdba52cc-0d56-11e6-8c7a-b9018a620374.png)

**Comment by denjello** [comment]
by the way, the new layout (with red on the top) should use the empty space at the top to allow the user to filter the locations...

**Comment by dasantonym** [comment]
i still don't like it and i think it is not fully thought through. why do we have a toolbar and then extend another toolbar from it (it is pretty much a toolshed and it can and will grow in complexity)? and why are the least important menu items on top of it (footer menu items)? and where do the search results extend (because apparently they aren't anymore, or at least in my chrome on the live site)? and how much space do you need for a configurable filter anyway (think preset list plus optional drop-down)?

![hmmm](https://cloud.githubusercontent.com/assets/566883/14889456/2c7c8488-0d5f-11e6-9947-a3346ed81e58.jpg)
